inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
    - db/**/*
    - vendor/**/*
    - node_modules/**/*
IfUnlessModifier:
  Enabled: false
Loop:
  Enabled: false
ClassLength:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
SignalException:
  Enabled: false
Documentation:
  Enabled: false
DotPosition:
  Enabled: false
RedundantBegin:
  Enabled: false
