sudo: false
addons:
  postgresql: '9.3'
  apt:
    packages:
    - libxslt1-dev
    - libxml2-dev
    - libmagic-dev
before_install:
- cd $TRAVIS_BUILD_DIR/src/$COMPONENT && bundle config build.nokogiri --use-system-libraries
before_script:
- cd $TRAVIS_BUILD_DIR/src/$COMPONENT && bundle exec rake $COMPONENT:travis:before_script
branches:
  only:
  - master
bundler_args: "--without development --jobs 7"
cache:
  apt: true
  bundler: true
  directories:
  - "$TRAVIS_BUILD_DIR/src/$COMPONENT/vendor/bundle"
env:
  matrix:
  - COMPONENT=supermarket
  - COMPONENT=fieri
language: ruby
notifications:
  email: false
  slack:
    secure: P9Mioa/7QFudKan2uKfJgP68xcvOLbLwqtjg5Sx1mnY41OzVKT4f5HM/T1gmhEC6s4nDlM/q+OBnNwOvi/5wNY+EkOFQsnfVlODsyVHdtPzo+421HD5mCIyIQocBSTsA720vGVHU3QNOM8hgnkTokWmFVVcF0Z66ICQMHzlS7E4=
rvm:
- 2.3.1
script:
- cd $TRAVIS_BUILD_DIR/src/$COMPONENT && bundle exec rake $COMPONENT:travis:script
services:
- redis-server
- postgresql
