---
driver:
  name: vagrant
  synced_folders:
    - ['../../../pkg', '/tmp/packages', 'create: true, type: :rsync']

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-10.04
  - name: centos-5.10

suites:
  - name: default
    run_list:
      - recipe[supermarket::cookbook_test]
    attributes:
      supermarket:
        test:
          deb_package_path: false
