---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-10.04
  - name: centos-5.10

suites:
  - name: default
    run_list:
      - recipe[supermarket::default]
    attributes:
