#
# Register your applications and add the appropiate keys and secrets.
#
# An example using GitHub
#
#   github:
#     key: MY_KEY
#     secret: MY_SECRET
#
# This file is actually parsed as ERB first, so you can use environment
# variables too:
#
#   github:
#     key: <%= ENV['GITHUB_OAUTH_KEY'] %>
#     secret: <%= ENV['GITHUB_OAUTH_SECRET'] %>
#

development:
  omni_auth:

production:
  omni_auth:

test:
  omni_auth:
