---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    data_bags_path: ../../data_bags
    role_path: roles
    run_list:
      - role[redis]
      - role[database]
      - role[web]
